# Generated by Django 6.0.6 on 2026-07-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_suspended_userprofile_suspended_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
